// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHm5WB03hybKHp72rqyGHpA88K5UBzaw',
    appId: '1:239803553427:web:8372d544c1cefbf364df66',
    messagingSenderId: '239803553427',
    projectId: 'auction-netherlands',
    authDomain: 'auction-netherlands.firebaseapp.com',
    storageBucket: 'auction-netherlands.firebasestorage.app',
    measurementId: 'G-450SELDKL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuIK_tZEFzMCdJ95eXcsftVxvSksKXLHE',
    appId: '1:239803553427:android:a482b5ebd03a31e064df66',
    messagingSenderId: '239803553427',
    projectId: 'auction-netherlands',
    storageBucket: 'auction-netherlands.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCqC36y09WRzIU-FuaSZ6ZVjpVtUwcgo',
    appId: '1:239803553427:ios:5fcee3f7d50ec85164df66',
    messagingSenderId: '239803553427',
    projectId: 'auction-netherlands',
    storageBucket: 'auction-netherlands.firebasestorage.app',
    iosBundleId: 'com.example.auction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtCqC36y09WRzIU-FuaSZ6ZVjpVtUwcgo',
    appId: '1:239803553427:ios:5fcee3f7d50ec85164df66',
    messagingSenderId: '239803553427',
    projectId: 'auction-netherlands',
    storageBucket: 'auction-netherlands.firebasestorage.app',
    iosBundleId: 'com.example.auction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlHm5WB03hybKHp72rqyGHpA88K5UBzaw',
    appId: '1:239803553427:web:a0f62fd69105654864df66',
    messagingSenderId: '239803553427',
    projectId: 'auction-netherlands',
    authDomain: 'auction-netherlands.firebaseapp.com',
    storageBucket: 'auction-netherlands.firebasestorage.app',
    measurementId: 'G-H0XFG242JB',
  );
}
